%% binImages.m

% Author: Sam Huguet 
% Author e-mail: samhuguet1@gmail.com

% Purpose: The function bins a folder of images to reduce their resolution. 

% Input data requirements: 
% The images are expected to be 2D, and have been
% produced by a Yokogawa CV7000S microscope. The image names are expected
% to be over 60 characters in length. 

% Function inputs: 
% folder_well [1×1 cell array] --> uipickfiles provides a string directory within a 1×1 cell array.
% doYouWantTobinImages [string] --> 'Yes' or 'No'. When set to 'Yes', the script will bin images. 
% scalingFactor [double] --> % A scaling factor of 0.5 is the equivant of binnning 2 by 2. 

% Function outputs: 
% folder_well [1×1 cell array] --> A string directory (within a 1×1 cell array) denoting the new directory of the binned images.

function folder_well = binImages(folder_well, doYouWantTobinImages, scalingFactor)

switch doYouWantTobinImages
    
    case 'No' 
        
        disp('You have chosen not to re-scale (bin) your images');
        
    case 'Yes' 

        disp('Re-scaling (binning) your images');
        
        %% Load up all the images in the folder. 

        % any funny single character names (e.g. '.') which I've seen appear.
        folder_well = cell2mat(folder_well);
        allFiles = dir(folder_well);
        allNames = {allFiles.name};
        numberOfImages = size(allNames);
        numberOfImages = numberOfImages(2);
        nameLength =  cellfun('length',allNames);
        logicalRepresentation = nameLength > 60;

        % Here are the correct names, generated by the process above. 
        correctNames = allNames(logicalRepresentation);
        numberOfCorrectNames = numel(correctNames);
        
        %% Loop through all the images, resize them and save them. 
        
        for t=1:numberOfCorrectNames
            
            if rem(t,10) == 0
            s1 = 'progress_t___ReScaling images ='; 
            value = num2str((t/numberOfCorrectNames)*100);
            message = cell2mat(strcat(s1,{' '}, value));
            disp(message);
            end 
            
            cd (folder_well)
            
            unscaledImage = imread(correctNames{t}); % Load in the unsclaed image. 
            
            scaledImage = imresize(unscaledImage, scalingFactor, 'bilinear'); % Scale the image. 
            
            s1 = folder_well;
            s2 = '\';
            s3 = 'ReScaled';
            RESCALEDdir = strcat(s1, s2, s3); % Construct the current directory that we want.
            if ~exist(RESCALEDdir, 'dir') % If the directory doesn't exist, then create it. 
                cd (folder_well)
                mkdir(RESCALEDdir)
            end
            
           cd (RESCALEDdir)
           imwrite(scaledImage, correctNames{t}, 'Compression', 'none');
            
        end 
        
        folder_well = {RESCALEDdir};
        
end 

disp('ReScaling complete');

end 